#!/usr/bin/env python
"""
Process Natural Earth data into GeoJSON format for the Earth screensaver.
Converts countries and cities from shapefiles to optimized GeoJSON/JS files.
"""

import json
import os
import sys

try:
    import geopandas as gpd
    import shapefile
except ImportError:
    print("ERROR: Required packages not installed. Run:")
    print("  pip install geopandas pyshp")
    sys.exit(1)

# Paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NE_DIR = os.path.join(BASE_DIR, "data", "natural-earth")
DATA_DIR = os.path.join(BASE_DIR, "src", "data")

# Input files
COUNTRIES_SHP = os.path.join(NE_DIR, "ne_10m_admin_0_countries.shp")
CITIES_SHP = os.path.join(NE_DIR, "ne_10m_populated_places.shp")

# Output files
COUNTRIES_JSON = os.path.join(DATA_DIR, "countries-ne.geo.json")
CITIES_JS = os.path.join(DATA_DIR, "cities-ne.js")

def process_countries():
    """Convert countries shapefile to GeoJSON with essential properties."""
    print("Processing countries...")

    # Read shapefile
    gdf = gpd.read_file(COUNTRIES_SHP)

    # Select and rename columns
    columns_to_keep = {
        'NAME': 'name',
        'ISO_A2': 'iso_a2',
        'ISO_A3': 'iso_a3',
        'POP_EST': 'population',
        'CONTINENT': 'continent',
        'REGION_UN': 'region',
        'geometry': 'geometry'
    }

    # Filter columns
    gdf_filtered = gdf[list(columns_to_keep.keys())].copy()
    gdf_filtered.columns = list(columns_to_keep.values())

    # Simplify geometries to reduce file size (tolerance in degrees, ~1km)
    print("  Simplifying geometries...")
    gdf_filtered['geometry'] = gdf_filtered['geometry'].simplify(tolerance=0.01)

    # Convert to GeoJSON
    print(f"  Writing to {COUNTRIES_JSON}...")
    geojson = json.loads(gdf_filtered.to_json())

    # Write formatted JSON
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(COUNTRIES_JSON, 'w', encoding='utf-8') as f:
        json.dump(geojson, f, ensure_ascii=False, separators=(',', ':'))

    file_size = os.path.getsize(COUNTRIES_JSON) / (1024 * 1024)
    print(f"  [OK] Created {COUNTRIES_JSON} ({file_size:.2f} MB)")
    print(f"  [OK] {len(gdf_filtered)} countries processed")

def process_cities():
    """Convert cities shapefile to JavaScript array format."""
    print("\nProcessing cities...")

    # Read shapefile using pyshp (faster for simple operations)
    sf = shapefile.Reader(CITIES_SHP)

    # Get field names
    field_names = [field[0] for field in sf.fields[1:]]  # Skip DeletionFlag

    # Find indices
    name_idx = field_names.index('NAME')
    lat_idx = field_names.index('LATITUDE')
    lon_idx = field_names.index('LONGITUDE')
    pop_idx = field_names.index('POP_MAX')
    country_idx = field_names.index('SOV0NAME')
    adm0cap_idx = field_names.index('ADM0CAP')  # 1 if capital, 0 otherwise

    cities_data = []

    for record in sf.records():
        name = record[name_idx]
        lat = record[lat_idx]
        lon = record[lon_idx]
        population = record[pop_idx]
        country = record[country_idx]
        is_capital = record[adm0cap_idx] == 1.0

        # Skip cities without coordinates
        if lat is None or lon is None:
            continue

        # Create city entry: [name, lat, lon, population, isCapital, country]
        cities_data.append([
            name,
            float(lat),
            float(lon),
            int(population) if population else 0,
            is_capital,
            country
        ])

    # Sort by population (descending) for better rendering priority
    cities_data.sort(key=lambda x: x[3], reverse=True)

    # Create JavaScript module
    js_content = f"""// Cities data from Natural Earth 1:10m Populated Places
// Format: [name, lat, lon, population, isCapital, country]
// Generated by scripts/process_natural_earth.py

export const cities = {json.dumps(cities_data, ensure_ascii=False, separators=(',', ':'))};

export default cities;
"""

    # Write JavaScript file
    print(f"  Writing to {CITIES_JS}...")
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(CITIES_JS, 'w', encoding='utf-8') as f:
        f.write(js_content)

    file_size = os.path.getsize(CITIES_JS) / (1024 * 1024)
    print(f"  [OK] Created {CITIES_JS} ({file_size:.2f} MB)")
    print(f"  [OK] {len(cities_data)} cities processed")

    # Print statistics
    capitals = sum(1 for city in cities_data if city[4])
    print(f"  [OK] {capitals} capitals, {len(cities_data) - capitals} other cities")

def main():
    """Main processing function."""
    print("=" * 60)
    print("Natural Earth Data Processor")
    print("=" * 60)

    # Check input files exist
    if not os.path.exists(COUNTRIES_SHP):
        print(f"ERROR: Countries shapefile not found: {COUNTRIES_SHP}")
        print("Please run the download script first.")
        sys.exit(1)

    if not os.path.exists(CITIES_SHP):
        print(f"ERROR: Cities shapefile not found: {CITIES_SHP}")
        print("Please run the download script first.")
        sys.exit(1)

    # Process data
    try:
        process_countries()
        process_cities()

        print("\n" + "=" * 60)
        print("[SUCCESS] Processing complete!")
        print("=" * 60)
        print(f"\nGenerated files:")
        print(f"  - {COUNTRIES_JSON}")
        print(f"  - {CITIES_JS}")

    except Exception as e:
        print(f"\nERROR: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
